Databases week1
RodrigoGuinsbergPinto/hyf-homework pull request #12
Opened 2023-01-12 10:58 UTC by RodrigoGuinsbergPinto

This is my database homework for Lesson1/week1.

2023-01-12 19:15 UTC, dboyadzhiev requested changes
pls, split your PR in two: one for DB and one for JS ohmeworks

2023-01-14 11:43 UTC, RodrigoGuinsbergPinto commented
> pls, split your PR in two: one for DB and one for JS ohmeworks

I will try. Just don't have a clue about how to do this.

2023-01-14 12:20 UTC, dboyadzhiev commented
> > pls, split your PR in two: one for DB and one for JS homework
> 
> I will try. Just don't have a clue about how to do this.

The easiest way, especially when you don't have experience with `git`, is to 
1. go to the branch `databases-week1`
2. copy your JS files (`javascript/javascript3/week1/`) somewhere, out of the project 
3. delete the folder (`javascript/javascript3/week1/`) from the project 
4. commit the changes
5. push the branch
6. done
7. go to the main branch 
8. create a new branch for `javascript3/week1/` 
9. copy back the files from `step 2` into the project
10. commit
11. push to the new JS branch

let me know if it helps

2023-01-14 16:45 UTC, RodrigoGuinsbergPinto commented
Hi dboyadzhiev, I did what you suggested.
Hope it worked.

2023-01-14 18:18 UTC, dboyadzhiev requested changes

2023-01-14 18:18 UTC, dboyadzhiev commented on databases/week1/lesson1_homework.sql
> +WHERE status_id = 3;
in this case, you should use `JOIN` with the `status` table.  
We don't know what id `3` stand for

2023-01-14 18:18 UTC, dboyadzhiev commented on databases/week1/lesson1_homework.sql
> +WHERE title REGEXP 'database' OR description REGEXP 'database';
The alternative is to use `like`
```suggestion
WHERE title like '%database%' OR description like '%database%';
```

2023-01-14 18:18 UTC, dboyadzhiev commented on databases/week1/lesson1_homework.sql
> +INNER JOIN status
you are missing the `ON` 
```suggestion
INNER JOIN status ON task.status_id = status.id
```

2023-01-14 18:18 UTC, dboyadzhiev commented on databases/week1/lesson1_homework.sql
> +SELECT status.name, COUNT(task.status_id) AS 'number_of_task'
the count should be by `task.id`
```suggestion
SELECT status.name, COUNT(task.id) AS 'number_of_task'
```

2023-01-14 18:18 UTC, dboyadzhiev commented on databases/week1/lesson1_homework.sql
> +GROUP BY task.status_id;
The `group by` should be by `status.name`
```suggestion
GROUP BY status.name;
```

2023-01-14 21:39 UTC, RodrigoGuinsbergPinto commented
Hi dboyadzhiev,
Thanks for the review.
Here is my file with suggested changes.

2023-01-15 08:25 UTC, dboyadzhiev approved these changes

2023-01-15 08:25 UTC, dboyadzhiev commented on databases/week1/lesson1_homework.sql
> +WHERE status_id = 3;
the ID of 'Done' can be different, so it is better to search by name instead
```suggestion
WHERE status.name = 'Done';
```

2023-01-17 10:04 UTC, RodrigoGuinsbergPinto commented
Hi Dimo, here is my last updated.
Thanks...

2023-01-17 10:42 UTC, dboyadzhiev requested changes
1 more thing :)

2023-01-17 10:42 UTC, dboyadzhiev commented on databases/week1/lesson1_homework.sql
> +ORDER BY status_id;
I didn't say it explicitly but this query should be looking like the one above :)

2023-01-18 07:55 UTC, RodrigoGuinsbergPinto commented
Hi Dimo,
Here is my file with changes to task 4.

2023-01-18 13:37 UTC, dboyadzhiev approved these changes

2023-01-22 11:05 UTC, merged