Javascript javascript1 week2
RodrigoGuinsbergPinto/hyf-homework pull request #4
Opened 2022-06-09 21:20 UTC by RodrigoGuinsbergPinto

Hi, here is my JS1-week2 homework.
I got a lot of extra help to finish it.

2022-06-15 15:42 UTC, Impressiv3 requested changes

2022-06-16 15:53 UTC, RodrigoGuinsbergPinto commented
Hi Bálint,
I have made the changes you suggested to the excess of comments, strict ===, switch statements and finished the candy function.
Thank you for the feedback.

2022-06-16 15:55 UTC, RodrigoGuinsbergPinto commented on javascript/javascript1/week2/js-week2.js
> +    if (total <= amountToSpend) {
Thanks. I fixed it.

2022-06-16 15:56 UTC, RodrigoGuinsbergPinto commented on javascript/javascript1/week2/js-week2.js
> +
Yes, I sure do. : )
Thanks.

2022-06-16 19:37 UTC, Impressiv3 commented
Very well done!  Good job !

2022-06-16 19:38 UTC, Impressiv3 approved these changes
I can see you already have merged it, but we still got some problems.
I will  contact you on Slack and we are going to fix them ;)

2022-06-17 09:22 UTC, merged