Javascript javascript2 week2
RodrigoGuinsbergPinto/hyf-homework pull request #8
Opened 2022-11-05 13:34 UTC by RodrigoGuinsbergPinto

Hi, in the first commit I added the wrong HTML file. 
I made a change to the file and committed again with 'correct files' description.

2022-11-14 18:17 UTC, annamourasobral requested changes
Hey, @RodrigoGuinsbergPinto 
Awesome work here! 
Besides us being both Brazilians, HYF's official language is English so I'll continue using it so everybody in the school can understand us. 😊
Let me know if you have any questions about the suggestions in Slack.
Keep going, and keep coding! 👩🏻‍💻

2022-11-14 18:17 UTC, annamourasobral commented on javascript/javascript2/week2/index2.html
> +          <input id="maxPrice" type="text" name="" class="max-price-input" />
```suggestion
          <input id="maxPrice" type="number" name="" class="max-price-input" />
```
It's always nice to be specific in which kind of input you're asking from the user.

2022-11-14 18:17 UTC, annamourasobral commented on javascript/javascript2/week2/index2.html
> +          <label class="form-label">Search for product</label>
```suggestion
          <label class="form-label">Search for product</label>
          <input id="searchInput" type="text" class="search-input" />
```
The label should be right before the input element that is referred to.

2022-11-14 18:17 UTC, annamourasobral commented on javascript/javascript2/week2/main.css
> +* {
Good job on CSS!

2022-11-14 18:17 UTC, annamourasobral commented on javascript/javascript2/week2/main.js
> +    // renderProducts(products);
```suggestion
    renderProducts(products);
```
If you comment on this, the list of products is gone when you erase the input. The same happens on maxPrice.

2022-11-14 18:17 UTC, annamourasobral commented on javascript/javascript2/week2/script.js
> +//     (movie.rating >= 7) ? "Good" : movie.rating >= 4 && movie.rating < 7 ? "Average" : "Bad";
movie.rating >= 7 ? "Good" : movie.rating >= 7 ? "Average" : "Bad";

I think this is what you're looking for.
[This article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator#conditional_chains),  will help you to understand clearly.

2022-11-14 19:29 UTC, materialsmoke commented
You're doing great!
I test it and it's working well

2022-11-18 10:04 UTC, RodrigoGuinsbergPinto commented on javascript/javascript2/week2/index2.html
> +          <input id="maxPrice" type="text" name="" class="max-price-input" />
Of course : )  Thank you for pointing that out.

2022-11-29 08:43 UTC, merged